--- #YAML:1.0
name:               Math-BigInt-Parts
version:            0.02
abstract:           split a Math::BigInt into signed mantissa and exponent
author:
    - Peter John Acklam <pjacklam@online.no>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
